### ISSUE TITLE
converting to modern Fortran with Milller's to_f90.f90

### ISSUE THREAD

**Issue by Beliavsky** [jacobwilliams/conmax#1]
Not an issue with your repo, just a comment.

I [forked your repo](https://github.com/Beliavsky/conmax) and ran Alan Miller's to_f90.f90 on conmax.f . It converts the code free source form and adds declarations with intents, but there are some problems with the automatic translation that prevents the resulting code from being compiled -- details at the repo. It would be great if a tool could create compilable modern Fortran from FORTRAN 77 code.

**Comment by jacobwilliams** [comment]
Cool! Yes, my intent was to see if this is actually a good algorithm and then to modernize it.

I've never entirely trusted `to_f90` though, since sometimes it gets things wrong or does weird things. Sometimes what I do is use these: https://github.com/ylikx/fortran-legacy-tools

like so:

```bash
python fixed2free2.py conmax.f > conmax.f901
python flowercase.py conmax.f901 > conmax.f90
```

and then manually update it. Maybe I can just use the `to_f90` results as a reference?

**Comment by jacobwilliams** [comment]
BTW, there used to be an online way to run a limited version of [SPAG](https://polyhedron.com/?product=plusfort#sp) but I don't think it's there anymore. That worked amazingly well for untangling spaghetti code. I wish somebody would buy it and just run it on every code in netlib!

**Comment by Beliavsky** [comment]
A limited version of SPAG is at https://fortran.uk/plusfortonline.php .
